PersonelMVCUI/Controllers/DepartmanController.cs
using PersonelMVCUI.Models.EntityFramework;
using PersonelMVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,B")]
 
    public class DepartmanController : Controller
    {
        PersonelDbEntities1 db = new PersonelDbEntities1();
        // GET: Home
       public ActionResult Test()
        {
            return View();
        }
        //ELMAH: HATALARI VERİTABANINA LOGLAMA İŞLEMİ
        //[HandleError]
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            //int a = 30, b = 0;
            //int c = a / b;
            return View(model);
        }
        [HttpGet]
        public ActionResult Yeni()
        {

            return View("DepartmanForm",new Departman());
        }
        //HttpPost yerine antiforgeryToken kullandık. saldırıların önüne geçmek için.
        //CSRF saldırılarının önüne geçmek için.
        [ValidateAntiForgeryToken]
        //kaydet ile hem güncelleme hem kayıt yapılmış oldu.
        public ActionResult Kaydet(Departman departman)
        {
            if(!ModelState.IsValid)
            {
                return View("DepartmanForm");
            }
            MesajViewModel model = new MesajViewModel();

            if(departman.Id==0)
            {
                db.Departman.Add(departman);
                model.Mesaj = departman.Ad + " başarıyla eklendi...";
            }
            else
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if(guncellenecekDepartman==null)
                {
                    return HttpNotFound();
                }
                guncellenecekDepartman.Ad = departman.Ad;
                model.Mesaj = departman.Ad + " başarıyla güncellendi...";
            }
            
            db.SaveChanges();
            model.Status = true;
            model.LinkTest = "Departman Listesi";
            model.Url = "/Departman";
            return View("_Mesaj",model);
        }
        //model içerisinde bulduysa textbox'a o stringi getirecek ona göre güncelleme yapılacak.
        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id);
            if (model == null)
                return HttpNotFound();
            return View("DepartmanForm",model); 
        }  
        public ActionResult Sil(int id)
        {
            var silinecekDepartman = db.Departman.Find(id);
            if (silinecekDepartman == null)
                return HttpNotFound();
            db.Departman.Remove(silinecekDepartman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PersonelMVCUI/Controllers/PersonelController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,B")]
    public class PersonelController : Controller
    {
        PersonelDbEntities1 db = new PersonelDbEntities1();
        // GET: Personel
        //[OutputCache(Duration =30)]
        public ActionResult Index()
        {
            //model değişkenin içinde include ile iki tablonun join işlemi yapıldı.(yani Eeager Loading yapıldı(sql'e tek sorgu gitmiş olacak))
            var model = db.Personel.Include(x=>x.Departman).ToList();
            return View(model);
        }
        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel=new Personel()
            };
            return View("PersonelForm",model);
        }
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if(!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model); 
            }
            if(personel.Id==0) //0'a eşitse ekleme yapılacak
            {
                db.Personel.Add(personel);
            }
            else  //Güncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm",model);
        }
        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            if(silinecekPersonel==null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x => x.Departman.Id == id).ToList();
            return PartialView(model);
        }
       public int? ToplamMaas()
        {
            return db.Personel.Sum(x => x.Maas);
        }
    }
}

PersonelMVCUI/Views/Departman/DepartmanForm.cshtml
@model PersonelMVCUI.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<form method="post" action="">
        <div class="form-group">
            <label>Departman Adı</label>
            <input type="text" name="Ad" class="form-control"/>
        </div>
        <button type="submit" class="btn btn-success">Ekle</button>
    </form>*@

@*bu yapının yerine HTML HELPER KULLANACAĞIZ.*@
@*Ajax BeginForm yapısı kullanıldı.*@

<div id="mesaj">

</div>
@using (Ajax.BeginForm("Kaydet", "Departman", new AjaxOptions { HttpMethod="POST",UpdateTargetId="mesaj"}))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Ad)
        @Html.TextAreaFor(m => m.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ad)

    </div>
    @Html.HiddenFor(m => m.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>
}

@section scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}

PersonelMVCUI/Views/Departman/Index.cshtml
@using PersonelMVCUI.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<a class="btn btn-success" href="/Departman/Yeni">Yeni Departman</a>
 <center><h3>Departman Listesi</h3><br /></center>
<table class="table table-bordered" id="tblDepartmanlar">
    <thead>
    <th>ID</th>
    <th>AD</th>
    <th>Guncelle</th>
    <th>Sil</th>
    <th>Personeller</th>


    </thead>
    <tbody>
        @foreach (var departman in Model) 
        {
            <tr>
                <td>@departman.Id</td>
                <td>@departman.Ad</td>
                <td><a class="btn btn-primary" href="/Departman/Guncelle/@departman.Id">Guncelle</a></td>
                <td><a class="btn btn-warning BtnDepartmanSil" data-id="@departman.Id">Sil</a></td>
                @*<<td>@Html.ActionLink("Personelleri Göster","PersonelleriListele","Personel", new {id=departman.Id },
                   new { @class="btn btn-primary"})</td>*@
                <td>@Ajax.ActionLink("Personelleri Göster","PersonelleriListele","Personel",new { id=departman.Id},
                   new AjaxOptions { HttpMethod="GET", UpdateTargetId="personelListesi"},new { @class="btn btn-primary"})</td>
            </tr>
        }

    </tbody>
</table>

<div id="personelListesi"></div>