PersonelMVCUI/Controllers/AddressController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,B")]
    public class AddressController : Controller
    {
        PersonelDbEntities1 db = new PersonelDbEntities1();
        // GET: Address
        public ActionResult Index()
        {
            var model = db.ADDRESS.Include(x => x.Personel).ToList();
            return View(model);
        }
        public ActionResult Yeni()
        {
            var model = new AddressFormViewModel()
            {
                Personeller = db.Personel.ToList(),
                Address = new ADDRESS()
            };

            return View("AddressForm",model);
        }
        public ActionResult Kaydet(ADDRESS address)
        {
            if (!ModelState.IsValid)
            {
                var model = new AddressFormViewModel()
                {
                    Personeller=db.Personel.ToList(),
                    Address=address
                };
                return View("AddressForm", model);
            }
            if(address.ID==0) //ekleme
            {
                db.ADDRESS.Add(address);
            }
            else  //güncelleme
            {
                db.Entry(address).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var model = new AddressFormViewModel()
            {
                Personeller = db.Personel.ToList(),
                Address = db.ADDRESS.Find(id)
            };
            return View("AddressForm", model); 
        }
        public ActionResult Sil(int id)
        {
            var silinecekAddress = db.ADDRESS.Find(id);
            if (silinecekAddress == null)
            {
                return HttpNotFound();
            }
            db.ADDRESS.Remove(silinecekAddress);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult AdresleriListele(int id)
        {
            var model = db.ADDRESS.Where(x => x.PERSONELID == id).ToList();
            return PartialView(model);
        }
    }
}

PersonelMVCUI/Controllers/PersonelController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A,B")]
    public class PersonelController : Controller
    {
        PersonelDbEntities1 db = new PersonelDbEntities1();
        // GET: Personel
        //[OutputCache(Duration =30)]
        public ActionResult Index()
        {
            //model değişkenin içinde include ile iki tablonun join işlemi yapıldı.(yani Eeager Loading yapıldı(sql'e tek sorgu gitmiş olacak))
            var model = db.Personel.Include(x=>x.Departman).ToList();
            return View(model);
        }
        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel=new Personel()
            };
            return View("PersonelForm",model);
        }
        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if(!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model); 
            }
            if(personel.Id==0) //0'a eşitse ekleme yapılacak
            {
                db.Personel.Add(personel);
            }
            else  //Güncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm",model);
        }
        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            if(silinecekPersonel==null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x => x.Departman.Id == id).ToList();
            return PartialView(model);
        }
       public int? ToplamMaas()
        {
            return db.Personel.Sum(x => x.Maas);
        }
    }
}

PersonelMVCUI/Views/Personel/Index.cshtml
@model List<PersonelMVCUI.Models.EntityFramework.Personel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <br />

@Html.ActionLink("Yeni Personel", "Yeni", null, new { @class = "btn btn-success" })
@DateTime.Now

<center><h2>Personel Listesi</h2><br /></center>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Departman</th>
            <th>Maaş</th>
            <th>Yaş</th>
            <th>Doğum Tarihi</th>
            <th>Cinsiyet</th>
            <th>Evlilik Durumu</th>
            <th>Güncelle</th>
            <th>Sil</th>
            <th>Adresler</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var personel in Model)
        {
        <tr>
            <td>@personel.Ad</td>
            <td>@personel.Soyad</td>
            <td>@personel.Departman.Ad</td>
            <td>@personel.Maas</td>
            <td>@(DateTime.Now.Year - personel.DogumTarihi.Value.Year) </td>
            <td>@personel.DogumTarihi.Value.ToString("dd-MM-yyyy")</td>
            <td>@(personel.Cinsiyet == true ? "Erkek" : "Kadın")</td>
            <td>@(personel.EvliMi == true ? "Evli" : "Bekar")</td>
            <td>@Html.ActionLink("Guncelle", "Guncelle", new { id = personel.Id }, new { @class = "btn btn-primary" })</td>
            <td>@Html.ActionLink("Sil", "Sil", new { id = personel.Id }, new { @class = "btn btn-warning" })</td>
            <td>@Ajax.ActionLink("Adres Bilgileri","AdresleriListele","Address", new {id=personel.Id },new AjaxOptions {HttpMethod="GET", UpdateTargetId="AdresListesi"},
               new { @class="btn btn-primary"})</td>
        </tr>
        }

    </tbody>

</table>
<div id="AdresListesi"></div>

PersonelMVCUI/Views/Personel/PersonelForm.cshtml
@model PersonelMVCUI.ViewModels.PersonelFormViewModel
@{
    ViewBag.Title = "PersonelForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Personel Formu</h2>
@Html.ValidationSummary()
@using (Html.BeginForm("Kaydet", "Personel", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Ad)
        @Html.TextBoxFor(m => m.Personel.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Personel.Ad)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Soyad)
        @Html.TextBoxFor(m => m.Personel.Soyad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Personel.Soyad)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.DepartmanId)
        @Html.DropDownListFor(m => m.Personel.DepartmanId, new SelectList(Model.Departmanlar, "Id", "Ad"),
      "Departman Seçiniz", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Personel.DepartmanId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.Maas)
        @Html.TextBoxFor(m => m.Personel.Maas, new { @class = "form-control" })
        @Html.ValidationMessageFor(m=>m.Personel.Maas)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Personel.DogumTarihi)
        @Html.TextBoxFor(m => m.Personel.DogumTarihi, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
        @Html.ValidationMessageFor(m => m.Personel.DogumTarihi)
    </div>
    <div class="radio">
        <label>
            @Html.RadioButtonFor(m => m.Personel.Cinsiyet, true) Erkek
        </label>
        <label>
            @Html.RadioButtonFor(m => m.Personel.Cinsiyet, false) Kadın
        </label>
        @Html.ValidationMessageFor(m => m.Personel.Cinsiyet)
    </div>
    <div class="radio">
        <label>
            @Html.RadioButtonFor(m => m.Personel.EvliMi, true) Evli
        </label>
        <label>
            @Html.RadioButtonFor(m => m.Personel.EvliMi, false) Bekar
        </label>
    </div>
    //Personel id'si gönderme hidden ile. Önemli!!!
    @Html.HiddenFor(m => m.Personel.Id)
    <button type="submit" class="btn btn-outline-danger">Kaydet</button>
}



@section scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
   
    <script>
        /*bu kod ile formdaki date'de veri girildiği halde zorunlu alan yazısı kalkmıyor idi şuanda çözüldü.*/
        $('input[data-val=true]').blur(function () {
            $(this).valid();
        });
    </script>
}

PersonelMVCUI/Views/Personel/PersonelleriListele.cshtml
@model IEnumerable<PersonelMVCUI.Models.EntityFramework.Personel>


<h1>Personel Listesi</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <td>Ad</td>
            <td>Soyad</td>
            <td>Doğum Tarihi</td>
            <td>Maaş</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var personel in Model)
        {
            <tr>
                <td>@personel.Ad</td>
                <td>@personel.Soyad</td>
                <td>@personel.DogumTarihi.Value.ToShortDateString()</td>
                <td>@personel.Maas</td>

            </tr>
        }

    </tbody>

</table>